/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import org.apache.http.HttpStatus;
import org.junit.BeforeClass;
import org.junit.Test;
import static io.restassured.RestAssured.*;
import static org.hamcrest.Matchers.*;
import io.restassured.response.Response;

public class AppTest {

    @BeforeClass
    public static void preConditions(){
        baseURI = "http://localhost";
        port = 3000;
    }

    @Test
    public void getUsuarios(){
        when()
                .get("/usuarios")
        .then()
                .statusCode(HttpStatus.SC_OK); /* 200 */
    }

    @Test
    public void postUsuarios(){
        // Envia a solicitação POST e extrai a resposta
        Response response = given()
                .body("{\n" +
                        "  \"nome\": \"Fulano da Silva X\",\n" +
                        "  \"email\": \"restassuredx@qa.com.br\",\n" +
                        "  \"password\": \"teste\",\n" +
                        "  \"administrador\": \"true\"\n" +
                        "}")
                .contentType("application/json")
                .when()
                .post("/usuarios")
                .then()
                .statusCode(HttpStatus.SC_CREATED) /* 201 */
                .body("message", is("Cadastro realizado com sucesso"))
                .extract().response();

        // Extrai o valor do "id" da resposta
        String userId = response.path("id");

        // Agora você pode usar o valor do "id" conforme necessário
        System.out.println("ID do usuário cadastrado: " + userId);
    }

}
